nodejs:
  # Don't modify below here
  image: https://hmcts.azurecr.io/hmcts/civil-citizen-ui:latest
  ingressHost: 
  keyVaults:
    civil-citizen-ui:
      resourceGroup: civil-citizen-ui
      secrets:
        - appinsights-instrumentation-key
        - draft-store-access-key
        - citizen-ui-idam-secret
        - name: ordnance-survey-api-key
          alias: ORDNANCE_SURVEY_API_KEY
        - cmc-s2s-secret
        - citizen-draft-store-primary
        - citizen-draft-store-secondary
  environment:
    ORDNANCE_SURVEY_API_KEY: 
    OAUTH_CLIENT_REDIRECT: https:///oauth2/callback
    IDAM_SIGN_OUT_REDIRECT_URL: https:///dashboard

