nodejs:
  # Don't modify below here
  image: https://hmcts.azurecr.io/hmcts/civil-citizen-ui:latest
  ingressHost: 
  environment:
    CIVIL_SERVICE_URL: http://civil-service-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal

idam-pr:
  enabled: false
