apiVersion: v2
appVersion: "1.0"
home: https://github.com/hmcts/idam-api
description: A Helm chart for CFT IDAM API
name: idam-api
version: 0.4.8
maintainers:
  - name: CFT IDAM Team
    email: reform.idam@HMCTS.NET
keywords:
- java
- web
- springboot
- postgres
- postgresql
- idam
- sidam
- idam-api
- api
dependencies:
  - name: java
    version: ~4.0.1
    repository: https://hmctspublic.azurecr.io/helm/v1/repo/
