# Don't modify this file, it is only needed for the pipeline to set the image and ingressHost
java:
  image: https://hmcts.azurecr.io/hmcts/lgy-iac-web:latest
  ingressHost: 

  environment:
    ENV_NAME: "Azure Dev PG"
    FLYWAY_USER: 
    FLYWAY_PASSWORD: 
    FLYWAY_URL: jdbc:postgresql://:5432/?&sslmode=require
    POSTGRES_HOST: 
    POSTGRES_PORT: "5432"
    POSTGRES_DATABASE: 
    POSTGRES_USER: 
    POSTGRES_PASSWORD: 
    POSTGRES_SSL_MODE: require
    DB_JDBC_DRIVER: "org.postgresql.Driver"
    DB_JDBC_URL: "jdbc:postgresql"
