nodejs:
  # Don't modify below here
  image: https://hmcts.azurecr.io/hmcts/et-sya:latest
  ingressHost: 
  environment:
    OAUTH_CLIENT_REDIRECT: https:///oauth2/callback
  keyVaults:
    et:
      resourceGroup: et
      secrets:
        - AppInsightsInstrumentationKey
        - idam-secret
        - redis-access-key
        - os-places-token

idam-pr:
  enabled: false
