java:
  postgresql:
    enabled: false
  releaseNameOverride: idam-web-admin
  image: hmctspublic.azurecr.io/idam/web-admin:preview
  ingressHost: "idam-web-admin.service.core-compute-{{ .Values.global.environment }}.internal"
  replicas: 1
  applicationPort: 8080
  aadIdentityName: idam
  keyVaults:
    "idam-idam":
      resourceGroup: idam-idam
      excludeEnvironmentSuffix: false
      secrets:
        - name: AppInsightsInstrumentationKey
          alias: azure.application-insights.instrumentation-key
  environment:
    STRATEGIC_SERVICE_URL: http://idam-api
    STRATEGIC_PUBLIC_URL: http://idam-web-public
    STRATEGIC_DASHBOARD_URL: https://idam-user-dashboard{{ .Values.global.environment }}.platform.hmcts.net
    ENDPOINTS_ENABLED: true
    MANAGEMENT_SECURITY_ENABLED: false
    SSL_VERIFICATION_ENABLED: true
    FEIGN_HTTPCLIENT_DISABLE_SSL_VALIDATION: false

  cpuRequests: '1000m'
  cpuLimits: '2500m'
  memoryRequests: '1024Mi'
  memoryLimits: '2048Mi'

  devmemoryRequests: '512Mi'
  devcpuRequests: '1000m'
  devmemoryLimits: '1024Mi'
  devcpuLimits: '2500m'

global:
  tenantId: "531ff96d-0ae9-462a-8d2d-bec7c0b42082"
  environment: preview
  enableKeyVaults: true
