# Don't modify this file, it is only needed for the pipeline to set the image and ingressHost
java:
  image: https://hmcts.azurecr.io/hmcts/wa-task-management-api:latest
  ingressHost: 
  devmemoryRequests: '512Mi'
  devcpuRequests: '1000m'
  devmemoryLimits: '3Gi'
  devcpuLimits: '2500m'

