apiVersion: v2
appVersion: "1.0"
description: A Helm chart for labs-matthewsearle01 App
name: labs-matthewsearle01
home: https://github.com/hmcts/labs-matthewsearle01
version: 0.0.1
maintainers:
  - name: HMCTS labs team
dependencies:
  - name: java
    version: 3.7.6
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
