nodejs:
  # Don't modify below here
  image: https://hmcts.azurecr.io/hmcts/pip-frontend:latest
  ingressHost: 
  environment:
    EXCLUDE_E2E: false
    AUTH_RETURN_URL: https:///login/return
    FRONTEND_URL: https://
