nodejs:
  # Don't modify below here
  image: https://hmcts.azurecr.io/hmcts/fact-admin:latest
  ingressHost: 
  environment:
    OAUTH_CLIENT_REDIRECT: https:///oauth2/callback
idam-pr:
  enabled: false
  redirect_uris:
    fact_admin:
      - https:///oauth2/callback
