# Don't modify this file, it is only needed for the pipeline to set the image and ingressHost
job:
  image: https://hmcts.azurecr.io/hmcts/hmc-operational-reports-runner:latest
  ingressHost: 
  kind: CronJob
  schedule: "0 01 02 ? * * *"
  startingDeadlineSeconds: 180
  concurrencyPolicy: Forbid
global:
  jobKind: CronJob
