nodejs:
  # Don't modify below here
  image: https://hmcts.azurecr.io/hmcts/prl-citizen-frontend:latest
  ingressHost: 
  keyVaults:
     prl:
       resourceGroup: prl
       secrets:
         - AppInsightsInstrumentationKey
idam-pr:
  enabled: false
