nodejs:
  # Don't modify below here
  image: https://hmcts.azurecr.io/hmcts/prl-citizen-frontend:latest
  ingressHost: 
  devmemoryLimits: 2Gi
  devmemoryRequests: 512Mi
  devcpuLimits: 1000m
  devcpuRequests: 500m
  keyVaults:
     prl:
       resourceGroup: prl
       secrets:
         - AppInsightsInstrumentationKey
         - prl-citizen-frontend-idam-client-secret
         - microservicekey-prl-citizen-frontend
         - system-update-user-username
         - system-update-user-password
         - idam-solicitor-username
         - idam-solicitor-password
idam-pr:
  enabled: true
  redirect_uris:
    prl-citizen-frontend:
      - https:///receiver
