nodejs:
  # Don't modify below here
  image: https://hmcts.azurecr.io/hmcts/prl-citizen-frontend:latest
  ingressHost: 
  devmemoryLimits: 2Gi
  devmemoryRequests: 512Mi
  devcpuLimits: 1000m
  devcpuRequests: 500m
  keyVaults:
     prl:
       resourceGroup: prl
       secrets:
         - AppInsightsInstrumentationKey
         - prl-cos-idam-client-secret
         - microservicekey-prl-cos-api
idam-pr:
  enabled: true
  redirect_uris:
    prl-citizen-frontend:
      - https:///receiver
