java:
  image: 'hmctspublic.azurecr.io/dm/store:latest'
  ingressHost: dm-store-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  readinessDelay: 40
  readinessTimeout: 5
  readinessPeriod: 15
  readinessFailureThreshold: 10
  livenessDelay: 40
  livenessTimeout: 5
  livenessPeriod: 15
  livenessFailureThreshold: 10
  applicationPort: '4603'
  aadIdentityName: dm-store
  keyVaults:
    dm:
      resourceGroup: dm-shared
      secrets:
        - name: RpaAppInsightsInstrumentationKey
          alias: azure.application-insights.instrumentation-key
        - name: dm-store-storage-account-primary-connection-string
          alias: azure.storage.connection-string
        - name: store-POSTGRES-PASS
          alias: spring.datasource.password
        - name: app-insights-connection-string
          alias: app-insights-connection-string
  environment:
    # db
    SPRING_DATASOURCE_PORT: 5432
    SPRING_DATASOURCE_NAME: evidence
    SPRING_DATASOURCE_OPTIONS: "?ssl=disable"
    SPRING_DATASOURCE_HOST: dm-store-postgres-db-v11-{{ .Values.global.environment }}.postgres.database.azure.com
    SPRING_DATASOURCE_USERNAME: evidence@dm-store-postgres-db-v11-{{ .Values.global.environment }}
    HIKARI_MAX_POOL_SIZE: 10

      # idam
    IDAM_USER_BASE_URI: 'https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net'
    IDAM_S2S_BASE_URI: 'http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal'

    RUN_DB_MIGRATION_ON_STARTUP: 'false'

    # Toggles
    ENABLE_IDAM_HEALTH_CHECK: 'false'
    ENABLE_METADATA_SEARCH: 'true'
    ENABLE_DOCUMENT_AND_METADATA_UPLOAD: 'false'
    ENABLE_FOLDER_API: 'true'
    ENABLE_DELETE: 'true'
    ENABLE_TTL: 'false'
    ENABLE_THUMBNAIL: 'true'
    ENABLE_METADATA_MIGRATION: 'false'
    ENABLE_OVERRIDE_METADATA: 'false'
    ENABLE_CHUNKING: 'false'
    ENABLE_ORPHAN_DOCUMENT_DELETION: 'false'

    LOG_OUTPUT: single
    ROOT_LOGGING_LEVEL: INFO
    LOG_LEVEL_SPRING_WEB: INFO
    LOG_LEVEL_SPRING_BATCH: INFO
    LOG_LEVEL_DM: INFO

    # Document Storage
    STORAGE_CONTAINER_DOCUMENT_CONTAINER_NAME: dm-store-docstore-{{ .Values.global.environment }}

    TASK_ENV: documentTaskLock-aat
    DOCUMENT_METADATA_UPDATE_MILLISECONDS: 3600000
    #Below File size limits are in MB
    MAX_MEDIA_FILE_SIZE: 500
    MAX_NON_MEDIA_FILE_SIZE: 1024

blobstorage:
  resourceGroup: dm-store-aks
  teamName: "CCD"
  location: uksouth
  setup:
    containers:
      - dm-docstore
  enabled: false
