java:
  environment:
    CALLBACK_DOMAIN: 
    CALLBACK_HTTP_HOST_PORT: 443
    CALLBACK_HTTP_SCHEME: https
  # Don't modify below here
  image: https://hmcts.azurecr.io/hmcts/em-ccdorc:latest
  ingressHost: 
