# Don't modify this file, it is only needed for the pipeline to set the image and ingressHost
nodejs:
  image: https://hmcts.azurecr.io/hmcts/darts-portal:latest
  ingressHost: 
  keyVaults:
    darts:
      secrets:
        - name: AppInsightsInstrumentationKey
          alias: APP_INSIGHTS_KEY

