nodejs:
  # Don't modify below here
  image: https://hmcts.azurecr.io/hmcts/nfdiv-frontend:latest
  ingressHost: 
  registerAdditionalDns:
    enabled: true
    prefix: civil
    primaryIngressHost: 
  environment:
    OAUTH_CLIENT_REDIRECT: https:///oauth2/callback
    IDAM_TOKEN_CACHE: true
    REDIS_HOST: 'nfdiv-frontend-{{ .Values.global.environment }}.redis.cache.windows.net'

idam-pr:
  enabled: false
