apiVersion: v2
appVersion: "1.0"
description: A Helm chart for ccd-migration App
name: ia-cron-ccd-migration-tool
home: https://github.com/hmcts/ccd-case-migration-starter
version: 0.0.4
maintainers:
  - name: HMCTS ccd team
dependencies:
  - name: job
    version: ~1.0.0
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
