java:
  # Don't modify below here
  image: https://hmcts.azurecr.io/hmcts/em-stitching:latest
  ingressHost: 
  environment:
    TASK_ENV: documentTaskLock-aat-staging
    HISTORIC_EXECUTIONS_RETENTION_ENABLED: 'false'
