java:
    environment:
        MANAGEMENT_ENDPOINT_HEALTH_CACHE_TIMETOLIVE: "30000"
        DOCMOSIS_SERVICE_DEV_MODE_FLAG: "true"
        PDF_TEST_ENABLED: "true"

    # Don't modify below here
    image: https://hmcts.azurecr.io/hmcts/prl-dgs:latest
    ingressHost: 
    keyVaults:
      prl:
        resourceGroup: prl
        secrets:
          - microservicekey-prl-dgs-api
          - docmosis-api-key
          - launchDarkly-sdk-key
          - AppInsightsInstrumentationKey
    aadIdentityName: prl
